services:
  - type: web
    name: rating-system-api
    env: image
    image: ghcr.io/kacperskimina/projekt-tdo:v1.0.1 # Używamy Twojego obrazu z CD!
    plan: free
    region: frankfurt
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: rating-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: rating-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: rating-db
          property: password

databases:
  - name: rating-db
    plan: free
    region: frankfurt