services:
  - type: web
    name: rating-system-api
    env: docker
    plan: free
    region: frankfurt
    dockerContext: ./backend/rating-system
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: rating-db
          property: connectionString

databases:
  - name: rating-db
    plan: free
    region: frankfurt