spring.application.name=movie-rating-system

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5453/movierating}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Serwer
server.port=${PORT:8080}

# Actuator 
management.endpoints.web.exposure.include=health,prometheus,metrics
management.prometheus.metrics.export.enabled=true
management.endpoint.health.show-details=always

# JWT Configuration
jwt.secret=${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongAndSecure123456}
jwt.expiration=86400000