spring.application.name=movie-rating-system

# SQLite
#spring.datasource.url=jdbc:sqlite:./data/movierating.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.jpa.database-platform=org.hibernate.community.dialects.SQLiteDialect
#spring.jpa.hibernate.ddl-auto=update

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5453/movierating
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator/Monitoring
management.endpoints.web.exposure.include=health,prometheus,metrics
management.prometheus.metrics.export.enabled=true

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongAndSecure123456
jwt.expiration=86400000