spring.application.name=movie-rating-system

# Konfiguracja pod PostgreSQL w Dockerze
spring.datasource.url=jdbc:postgresql://postgres_db:5432/movierating
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialekt Hibernate dla Postgresa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Monitoring (Twoje metryki)
management.endpoints.web.exposure.include=health,prometheus,metrics
management.prometheus.metrics.export.enabled=true
management.endpoint.health.show-details=always

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongAndSecure123456
jwt.expiration=86400000