name: CI - Build and Lint

on:
  push:
    branches: [ "main", "infra/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Checkstyle (Linting)
        # To polecenie uruchamia testy i plugin checkstyle dodany do pom.xml
        run: mvn verify 
        working-directory: ./backend/rating-system
